### ISSUE TITLE
Improve search performance and simply logic.

### ISSUE THREAD

**Issue by bwanamaina** [KWangechi/bank-codes-web-scrapper#11]
This PR aims to improve performance and separate search logic from the main application entry point(components) into custom hook(s).
Currently search is triggered on every keystroke and the current results (UI) is replaced by skeleton and timeout is used to control the UI, this can be improved.

### Proposal

- Extract Search input into a separate component.
- Debounce the search input onChange logic using a custom timed hook to ensure search is performed for a term instead of triggering it on every keystroke.
- Extract search logic into a custom hook and remove the setTimeout when filtering banks. 
- Instead of showing skeleton when searching, highlight the matched search in the bank name/branch (this is optional but serves the purpose of showing user that filtering is happening as the type). 

![Screenshot 2024-08-04 at 16 59 42](https://github.com/user-attachments/assets/fb6a6e6e-0526-48cc-ac4b-e6751854a796)

**Comment by KWangechi** [comment]
May also need to enable one to search "Bank Branch', 'Branch, Bank', 'Alias, Branch' ... e.g "KCB Ruiru' wields a 'No results found card'...

When searching just 'Ruiru' or 'KCB' individually, it works, however if used together, it doesn't work

**Individually**
![image](https://github.com/user-attachments/assets/6ad20d40-18c5-491b-8f64-27700cefa51c) 


**Separately** 
![image](https://github.com/user-attachments/assets/7edc9b2f-0622-4ec0-9341-3e4433c7f2cf)

**Comment by bwanamaina** [comment]
I will open a PR to handle this logic.
